name: LAO Test
favicon: null
layout_spectrum: 0.31556
typography_spectrum: 0.60975
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: LAO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#651F01'
    - '#FFFFFF'
    - '#170C0C'
    - '#918888'
    - '#9A5C39'
  brandStrength: 0.5625
  lightness: 0.1949517
  saturation: 0.422545
  rhythmicContrast: 0.8619764
purpose: []
