analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4225450167432427
  brandStrength: 0.8093448
  lightness: 0.1507979808375239
  brandColors:
    - '#651F01'
    - '#FFFFFF'
    - '#170C0C'
    - '#918888'
    - '#9A5C39'
  rhythmicContrast: 0.953341914108023
typography_spectrum: 0.8823845
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3474758
favicon: null
name: LAO Test
