favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.422545
  brandStrength: 0.5042965
  lightness: 0.1949517
  brandColors:
    - '#651F01'
    - '#FFFFFF'
    - '#170C0C'
    - '#918888'
    - '#9A5C39'
  rhythmicContrast: 0.8619764
typography_spectrum: 0.8780881
layout_spectrum: 0.3474758
cta:
  bucket: null
  version: null
  domain: null
name: LAO Test
