name: LAO Test
favicon: null
layout_spectrum: 0.17579
typography_spectrum: 0.42684
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: LAO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DFE8EB'
    - '#77B5B3'
    - '#398778'
    - '#161617'
    - '#FBE0AC'
  brandStrength: 0.5042965
  lightness: 0.5
  saturation: 0.422545
  rhythmicContrast: 0.8619764
purpose: []
